import { useMemo } from 'react';
import type { QuranSegmentUI } from '../types/types';
import { sectionValidationSchema } from '@/Validation/dailyMarksValidation';
import * as yup from 'yup';

export const useSectionValidation = (
  memorizationMeta: QuranSegmentUI[] | undefined, 
  reviewMeta: QuranSegmentUI[] | undefined
) => {
  
  const consistencyErrors = useMemo(() => {
    const errors: string[] = [];
    if (!memorizationMeta || !reviewMeta) return errors;

    // 1. Run Yup Schema Validation for Consistency
    try {
      // Create a minimal object matching SectionFormData to partial validate
      // We only care about the 'consistency-check' test in the schema
      sectionValidationSchema.validateSync({
        date: '2023-01-01', // Dummy date to pass check
        memorizationMeta: memorizationMeta,
        reviewMeta: reviewMeta
      }, { abortEarly: false });

    } catch (err: any) {
      if (err instanceof yup.ValidationError) {
        err.inner.forEach((validationError: any) => {
           // We only want errors related to consistency (reviewMeta errors generated by the test)
           // The test in dailyMarksValidationTarget uses 'reviewMeta' as path or custom message
           if (validationError.path === 'reviewMeta' || validationError.type === 'consistency-check') {
               errors.push(`🚫 ${validationError.message}`);
           }
        });
      }
    }

    // 2. Check internal UI errors (populated by specialized components like QuranSegmentInput)
    // These are separate from "Consistency" but user wants all alerts "in modal"
    reviewMeta.forEach((rev) => {
      if (rev.error) {
           errors.push(`🚫 ${rev.error}`);
      }
    });

    memorizationMeta.forEach(mem => {
        if (mem.error) {
            errors.push(`🚫 ${mem.error}`);
        }
    });

    return errors;
  }, [memorizationMeta, reviewMeta]);

  const hasConsistencyErrors = consistencyErrors.length > 0;

  return {
    consistencyErrors,
    hasConsistencyErrors
  };
};
