const mongoose = require("mongoose");
const Attendance = require("../../schema/Attendance");
const Section = require("../../schema/DailyMark/Section");
const Student = require("../../schema/Student/Student");
const { TIMEZONE } = require('../../config/timezone');

// Create or update attendance records for a specific date
exports.createAttendance = async (req, res) => {
  try {
    const { date, records } = req.body;
    
    // Note: Validation is now handled by validate() middleware using Zod schema
    
    // 1. Date Parsing - ✅ FIX: Use UTC to match Section.dateKey
    // Parse the date and create a UTC midnight date
    const inputDate = new Date(date);
    const dateKey = inputDate.toISOString().split('T')[0]; // YYYY-MM-DD in UTC
    
    // Create a proper UTC midnight date for storage
    const formattedDate = new Date(dateKey + 'T00:00:00.000Z');
    
    console.log(`📅 [Attendance] Input date: ${date}, dateKey: ${dateKey}, formattedDate: ${formattedDate.toISOString()}`);

    // 2. Check if date is in the future or too old ( > 7 days)
    const now = new Date();
    const todayKey = now.toISOString().split('T')[0];
    const todayUTC = new Date(todayKey + 'T00:00:00.000Z');
    
    // Check for future dates
    if (formattedDate > todayUTC) {
      return res.status(403).json({
        message: "لا يمكن تسجيل الحضور لتاريخ مستقبلي",
        details: "يجب تسجيل الحضور لليوم الحالي أو الأيام السابقة فقط.",
        isFutureDate: true
      });
    }

    const ONE_WEEK = 7 * 24 * 60 * 60 * 1000;
    const timeDiff = todayUTC - formattedDate;
    if (timeDiff > ONE_WEEK) {
      const daysAgo = Math.round(timeDiff / (1000 * 60 * 60 * 24));
      return res.status(403).json({
        message: "لا يمكن تعديل الحضور بعد مرور أسبوع",
        details: `هذا التاريخ قديم (مضى عليه ${daysAgo} يوم).`,
        daysAgo,
      });
    }

    // 3. Prepare Records
    const attendanceRecords = [];
    const studentIds = [];
    
    for (const record of records) {
      attendanceRecords.push({
        studentId: record.studentId,
        date: formattedDate,
        isPresent: record.isPresent,
      });
      studentIds.push(record.studentId);
    }

    // 🆕 Check if Section (Segment) exists for this date and group
    // attendance is restricted to dates where a section exists.
    if (studentIds.length > 0) {
      const firstStudent = await Student.findOne({ _id: studentIds[0] }).select('group');
      if (firstStudent && firstStudent.group) {
         // ✅ FIX: Use dateKey (UTC-based) for consistent date matching
         // This avoids timezone issues where local 00:00 doesn't match UTC dates
         const dateKey = formattedDate.toISOString().split('T')[0];
         
         console.log(`🔍 [Attendance] Checking Section for group: ${firstStudent.group}, dateKey: ${dateKey}`);

         const hasSection = await Section.exists({
            group: firstStudent.group,
            dateKey: dateKey  // ✅ Match by dateKey string instead of Date range
         });

         console.log(`🔍 [Attendance] Section exists: ${!!hasSection}`);

         if (!hasSection) {
             return res.status(403).json({
                 message: "عذراً، لا يمكن تسجيل الحضور لهذا التاريخ",
                 details: "يجب فتح الحصة وتسجيل المقاطع في سجل المتابعة اليومي أولاً قبل أخذ الحضور."
             });
         }
      }
    }

    // 4. Fetch Old Records (for notifications)
    // We do this before deletion to know who changed status
    let oldRecordsMap = new Map();
    try {
      const oldRecords = await Attendance.find({
        studentId: { $in: studentIds },
        date: formattedDate, // Exact match since we set hours to 0
      }).select('studentId isPresent createdAt').lean();

      oldRecords.forEach(r => {
        oldRecordsMap.set(r.studentId.toString(), r);
      });
    } catch (e) {
      console.error("Error fetching old records:", e);
    }

    // 6. Upsert Records (Update if exists, Insert if not)
    // ✅ أفضل من Delete + Insert - يضمن سجل واحد لكل طالب/تاريخ
    const bulkOps = attendanceRecords.map(record => ({
      updateOne: {
        filter: { 
          studentId: record.studentId, 
          date: record.date 
        },
        update: { 
          $set: { 
            isPresent: record.isPresent,
            autoGenerated: false // تم تسجيله يدوياً
          } 
        },
        upsert: true // إنشاء جديد إذا غير موجود
      }
    }));

    const bulkResult = await Attendance.bulkWrite(bulkOps, { ordered: false });
    
    console.log(`📋 [Attendance] Upsert result: ${bulkResult.upsertedCount} new, ${bulkResult.modifiedCount} updated`);

    // 8. Send Response Immediately (Optimistic)
    res.status(201).json({ 
      message: "تم حفظ سجل الحضور بنجاح",
      stats: {
        new: bulkResult.upsertedCount,
        updated: bulkResult.modifiedCount
      }
    });

    // 9. Background Tasks (Notifications & Sockets)
    // We don't await these to keep the response fast
    (async () => {
      try {
        // A. Notifications
        if (global.notificationService) {
          const teacherName = req.user?.firstName
            ? `${req.user.firstName} ${req.user.lastName || ""}`.trim()
            : "المعلم";
          const dateStr = formattedDate.toLocaleDateString("ar-SA", { timeZone: TIMEZONE });

          // Notify Absents
          const absentRecords = attendanceRecords.filter(r => !r.isPresent);
          for (const record of absentRecords) {
            global.notificationService.notifyAbsence(record.studentId, dateStr, teacherName)
              .catch(e => console.error(`Notification error for ${record.studentId}:`, e.message));
          }

          // Notify Absence Removals
          for (const record of attendanceRecords) {
            const oldRecord = oldRecordsMap.get(record.studentId.toString());
            if (oldRecord && !oldRecord.isPresent && record.isPresent) {
              // Check if within 7 days (already checked above, but good for safety)
              if (timeDiff <= ONE_WEEK) {
                global.notificationService.notifyAbsenceRemoved(record.studentId, dateStr, teacherName)
                  .catch(e => console.error(`Removal notification error for ${record.studentId}:`, e.message));
              }
            }
          }
        }

        // B. Socket.IO Updates
        if (global.io) {
          // Emit simple update
          global.io.to("attendance").emit("attendanceCreated", {
            date: formattedDate,
            count: attendanceRecords.length, // ✅ استخدام attendanceRecords بدلاً من insertResult
            newCount: bulkResult.upsertedCount,
            updatedCount: bulkResult.modifiedCount,
            timestamp: Date.now(),
          });

          // Emit Dashboard Update (Admin)
          // Calculate absent students for today/tomorrow to update dashboard
          // ✅ FIX: Use UTC dates for consistent matching
          const nowForSocket = new Date();
          const todayKeySocket = nowForSocket.toISOString().split('T')[0];
          const todaySocket = new Date(todayKeySocket + 'T00:00:00.000Z');
          const nextDaySocket = new Date(todayKeySocket + 'T00:00:00.000Z');
          nextDaySocket.setUTCDate(nextDaySocket.getUTCDate() + 1);

          // Only run aggregation if the updated date is TODAY
          if (formattedDate.getTime() === todaySocket.getTime()) {
            const absentStudents = await Attendance.aggregate([
              { $match: { date: { $gte: todaySocket, $lt: nextDaySocket }, isPresent: false } },
              { $lookup: { from: "students", localField: "studentId", foreignField: "_id", as: "student" } },
              { $unwind: "$student" },
              { $lookup: { from: "groups", localField: "student.group", foreignField: "name", as: "groupInfo" } },
              { $unwind: { path: "$groupInfo", preserveNullAndEmptyArrays: true } },
              { $lookup: { from: "teachers", localField: "groupInfo.teacher", foreignField: "_id", as: "teacherInfo" } },
              { $unwind: { path: "$teacherInfo", preserveNullAndEmptyArrays: true } },
              {
                $project: {
                  _id: "$student._id",
                  fullName: { $concat: ["$student.firstName", " ", "$student.lastName"] }, // Simplified for speed
                  teacher: { $concat: ["$teacherInfo.firstName", " ", "$teacherInfo.lastName"] },
                  group: "$student.group"
                }
              }
            ]);

            global.io.to("admin-room").emit("absentStudentsUpdated", {
              date: formattedDate,
              timestamp: Date.now(),
              data: absentStudents,
              count: absentStudents.length,
            });
          }
        }
      } catch (bgError) {
        console.error("Background task error:", bgError);
      }
    })();

  } catch (error) {
    console.error("Error creating attendance records:", error);
    // Handle duplicate key error specifically if it happens
    if (error.code === 11000) {
      return res.status(201).json({ message: "تم الحفظ (مع وجود تكرار)" });
    }
    res.status(500).json({
      message: "حدث خطأ أثناء حفظ سجل الحضور",
      error: error.message,
    });
  }
};
